// <auto-generated />
namespace DemoDatabaseTester.WebSuiteDataMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstInitialisation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstInitialisation));
        
        string IMigrationMetadata.Id
        {
            get { return "201508021616597_FirstInitialisation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
